services:
  # SERVICIO 1: El Bot de Telegram (DavoGram)
  davogram:
    build: .
    container_name: davogram_container
    restart: unless-stopped
    command: python main.py
    volumes:
      - ./data:/app/data
      - ./my_account.session:/app/my_account.session
      - ./my_account.session-journal:/app/my_account.session-journal
      - ./downloads:./downloads

  # SERVICIO 2: El Userbot de Descargas (Userbot Drive)
  userbot-drive:
    build: .
    container_name: userbot_drive_container
    restart: unless-stopped
    # Ejecutamos específicamente el script del userbot
    command: python userbot_drive.py
    volumes:
      # Comparten la misma sesión y base de datos para estar sincronizados
      - ./data:/app/data
      - ./my_account.session:/app/my_account.session
      - ./my_account.session-journal:/app/my_account.session-journal
      # ¡Vital para que las pelis lleguen a Drive!
      - ./downloads:./downloads
